#!/bin/bash

tc () { echo $1 | gsed -e 's/\<./\U&/'; }

for post in _posts/* ; do
  for category in $( grep categories: $post | sed 's/categories://' ) ; do
    echo $category
    if [ -e category/$category.html ] ; then
      echo category/$category.html already exists
    else
      cat <<EOF > category/$category.html
---
layout: category
title: $(tc $category)
category: $category
---
EOF
    fi
  done
done
